/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lottoappphase2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Francis
 */
public class PhaseTwo extends javax.swing.JFrame {

    /**
     * Creates new form PhaseTwo
     */
    public PhaseTwo() {
        initComponents();
    }
    int input;
    int input1;
    int input2;
    int input3;
    int input4;
    int input5;
    int guess;
    int rand[] = new int[5];

    //lotto plus one variables
    int inputl;
    int inputl1;
    int inputl2;
    int inputl3;
    int inputl4;
    int inputl5;
    int guessl;

    // lotto plus two variables
    int randlo[] = new int[5];
    int inputlt;
    int inputlt1;
    int inputlt2;
    int inputlt3;
    int inputlt4;
    int inputlt5;
    int guess2;

    int randlt[] = new int[5];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lottoGamelbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputar = new javax.swing.JTextArea();
        numtf3 = new javax.swing.JTextField();
        numtf4 = new javax.swing.JTextField();
        numtf1 = new javax.swing.JTextField();
        numtf2 = new javax.swing.JTextField();
        Finishbtn = new javax.swing.JButton();
        numtf = new javax.swing.JTextField();
        error = new javax.swing.JPanel();
        errorDisplay = new javax.swing.JLabel();
        filestatus = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        insertNumberBelowlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordar = new javax.swing.JTextArea();
        generatebtn = new javax.swing.JButton();
        numtf5 = new javax.swing.JTextField();
        insertNumberBelowlbl1 = new javax.swing.JLabel();
        generatebtn1 = new javax.swing.JButton();
        numtf6 = new javax.swing.JTextField();
        numtf7 = new javax.swing.JTextField();
        numtf8 = new javax.swing.JTextField();
        numtf9 = new javax.swing.JTextField();
        numtf10 = new javax.swing.JTextField();
        insertNumberBelowlbl2 = new javax.swing.JLabel();
        generatebtn2 = new javax.swing.JButton();
        numtf11 = new javax.swing.JTextField();
        numtf12 = new javax.swing.JTextField();
        numtf13 = new javax.swing.JTextField();
        numtf14 = new javax.swing.JTextField();
        Finishbtn1 = new javax.swing.JButton();
        Finishbtn2 = new javax.swing.JButton();
        recordAllbtn = new javax.swing.JButton();
        recordbtn = new javax.swing.JButton();
        backToHomebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        recordAllbtn1 = new javax.swing.JButton();
        recordbtn1 = new javax.swing.JButton();
        recordAllbtn2 = new javax.swing.JButton();
        recordbtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 102, 0));

        lottoGamelbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lottoGamelbl.setText("Lotto Game");

        outputar.setBackground(new java.awt.Color(204, 204, 204));
        outputar.setColumns(20);
        outputar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        outputar.setRows(5);
        jScrollPane2.setViewportView(outputar);

        numtf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf3ActionPerformed(evt);
            }
        });

        numtf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf4ActionPerformed(evt);
            }
        });

        numtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf1ActionPerformed(evt);
            }
        });

        numtf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf2ActionPerformed(evt);
            }
        });

        Finishbtn.setBackground(new java.awt.Color(0, 204, 204));
        Finishbtn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Finishbtn.setForeground(new java.awt.Color(204, 0, 0));
        Finishbtn.setText("Play Lotto");
        Finishbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishbtnActionPerformed(evt);
            }
        });

        numtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtfActionPerformed(evt);
            }
        });

        error.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 7, true));

        errorDisplay.setBackground(new java.awt.Color(102, 102, 0));
        errorDisplay.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        errorDisplay.setForeground(new java.awt.Color(153, 153, 0));
        errorDisplay.setText("All errors will be displayed here");

        status.setBackground(new java.awt.Color(0, 255, 102));
        status.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        status.setForeground(new java.awt.Color(255, 51, 0));
        status.setText("This is the File Status");

        javax.swing.GroupLayout errorLayout = new javax.swing.GroupLayout(error);
        error.setLayout(errorLayout);
        errorLayout.setHorizontalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorLayout.createSequentialGroup()
                .addGroup(errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(457, 457, 457)
                .addComponent(filestatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        errorLayout.setVerticalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filestatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(errorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(errorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        insertNumberBelowlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        insertNumberBelowlbl.setForeground(new java.awt.Color(0, 102, 51));
        insertNumberBelowlbl.setText("Insert Numbers Below");

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 102, 0), null, null));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Your Record");

        recordar.setColumns(20);
        recordar.setRows(5);
        jScrollPane1.setViewportView(recordar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel4)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        generatebtn.setBackground(new java.awt.Color(255, 102, 0));
        generatebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generatebtn.setText("Click and Start");
        generatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebtnActionPerformed(evt);
            }
        });

        numtf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf5ActionPerformed(evt);
            }
        });

        insertNumberBelowlbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        insertNumberBelowlbl1.setForeground(new java.awt.Color(0, 102, 51));
        insertNumberBelowlbl1.setText("Insert Numbers Below");

        generatebtn1.setBackground(new java.awt.Color(255, 102, 0));
        generatebtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generatebtn1.setText("Click and Start");
        generatebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebtn1ActionPerformed(evt);
            }
        });

        numtf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf6ActionPerformed(evt);
            }
        });

        numtf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf7ActionPerformed(evt);
            }
        });

        numtf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf8ActionPerformed(evt);
            }
        });

        numtf9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf9ActionPerformed(evt);
            }
        });

        numtf10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf10ActionPerformed(evt);
            }
        });

        insertNumberBelowlbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        insertNumberBelowlbl2.setForeground(new java.awt.Color(0, 102, 51));
        insertNumberBelowlbl2.setText("Insert Numbers Below");

        generatebtn2.setBackground(new java.awt.Color(255, 102, 0));
        generatebtn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generatebtn2.setText("Click and Start");
        generatebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebtn2ActionPerformed(evt);
            }
        });

        numtf11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf11ActionPerformed(evt);
            }
        });

        numtf12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf12ActionPerformed(evt);
            }
        });

        numtf13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf13ActionPerformed(evt);
            }
        });

        numtf14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf14ActionPerformed(evt);
            }
        });

        Finishbtn1.setBackground(new java.awt.Color(0, 204, 204));
        Finishbtn1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Finishbtn1.setForeground(new java.awt.Color(204, 0, 0));
        Finishbtn1.setText("Play Lotto  PLus Two");
        Finishbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Finishbtn1ActionPerformed(evt);
            }
        });

        Finishbtn2.setBackground(new java.awt.Color(0, 204, 204));
        Finishbtn2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Finishbtn2.setForeground(new java.awt.Color(204, 0, 0));
        Finishbtn2.setText("PLay Lotto PLus One");
        Finishbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Finishbtn2ActionPerformed(evt);
            }
        });

        recordAllbtn.setBackground(new java.awt.Color(153, 0, 0));
        recordAllbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recordAllbtn.setText("save");
        recordAllbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordAllbtnActionPerformed(evt);
            }
        });

        recordbtn.setBackground(new java.awt.Color(255, 255, 0));
        recordbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recordbtn.setText("Display File");
        recordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtnActionPerformed(evt);
            }
        });

        backToHomebtn.setBackground(new java.awt.Color(51, 204, 0));
        backToHomebtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        backToHomebtn.setForeground(new java.awt.Color(153, 0, 153));
        backToHomebtn.setText("Home");
        backToHomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomebtnActionPerformed(evt);
            }
        });

        resetbtn.setBackground(new java.awt.Color(0, 0, 204));
        resetbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        resetbtn.setText("reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        recordAllbtn1.setBackground(new java.awt.Color(153, 0, 0));
        recordAllbtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recordAllbtn1.setText("save");
        recordAllbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordAllbtn1ActionPerformed(evt);
            }
        });

        recordbtn1.setBackground(new java.awt.Color(255, 255, 0));
        recordbtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recordbtn1.setText("Display File");
        recordbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtn1ActionPerformed(evt);
            }
        });

        recordAllbtn2.setBackground(new java.awt.Color(153, 0, 0));
        recordAllbtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recordAllbtn2.setText("save");
        recordAllbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordAllbtn2ActionPerformed(evt);
            }
        });

        recordbtn2.setBackground(new java.awt.Color(255, 255, 0));
        recordbtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recordbtn2.setText("Display File");
        recordbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertNumberBelowlbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(recordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(recordAllbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(34, 34, 34))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Finishbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(numtf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(numtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(numtf2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(numtf3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(numtf4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(recordAllbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Finishbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(recordbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(recordAllbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(generatebtn2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(insertNumberBelowlbl2, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(recordbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(insertNumberBelowlbl1)
                                    .addComponent(generatebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(numtf10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numtf11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numtf12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numtf13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numtf14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numtf5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numtf6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numtf7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numtf8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numtf9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(238, 238, 238)
                            .addComponent(Finishbtn2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(backToHomebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(lottoGamelbl))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lottoGamelbl)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(insertNumberBelowlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(numtf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numtf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numtf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Finishbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recordAllbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(generatebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(insertNumberBelowlbl1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numtf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numtf11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numtf12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numtf13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numtf14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generatebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(insertNumberBelowlbl2)
                                .addGap(32, 32, 32)
                                .addComponent(Finishbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recordAllbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recordbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backToHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numtf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numtf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numtf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numtf8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numtf9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(Finishbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(recordAllbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recordbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numtf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf3ActionPerformed

    private void numtf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf4ActionPerformed

    private void numtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf1ActionPerformed

    private void numtf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf2ActionPerformed

    private void backToHomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomebtnActionPerformed
        // TODO add your handling code here:
        //this will send you back to the home
        GameGUI myGUI = new GameGUI();
        myGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backToHomebtnActionPerformed

    private void recordAllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordAllbtnActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String input = (numtf.getText());
        String input1 = (numtf1.getText());
        String input2 = (numtf2.getText());
        String input3 = (numtf3.getText());
        String input4 = (numtf4.getText());

        try {

            outFile = new File("SecondPhaseLotto.txt");

            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(input);
            bw.write(input1);
            bw.write(input2);
            bw.write(input3);
            bw.write(input4 + ".....//");
            bw.newLine();

            bw.close();

        } catch (IOException e) {
            errorDisplay.setText("Error writing to file" + e);
            System.out.println("Error writing to file" + e);
        }
        status.setText("your Lotto file was created");

    }//GEN-LAST:event_recordAllbtnActionPerformed

    private void recordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtnActionPerformed
        String input;
        String input1;
        String input2;
        String input3;
        String input4;

        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("SecondPhaseLotto.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            input = br.readLine();
            input1 = br.readLine();
            input2 = br.readLine();
            input3 = br.readLine();
            input4 = br.readLine();

            recordar.setText(input + "...||  " + input1 + "...||  " + input2 + "...||  " + input3 + "...||  " + input4);
        } catch (IOException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_recordbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        Finishbtn.setEnabled(true);
        Finishbtn1.setEnabled(true);
        Finishbtn2.setEnabled(true);
        numtf.setText("");
        numtf1.setText("");
        numtf2.setText("");
        numtf3.setText("");
        numtf4.setText("");
        numtf5.setText("");
        numtf6.setText("");
        numtf7.setText("");
        numtf8.setText("");
        numtf9.setText("");
        numtf10.setText("");
        numtf11.setText("");
        numtf12.setText("");
        numtf13.setText("");
        numtf14.setText("");
        recordar.setText("");

        outputar.setText("");
        guess = 0;
        guessl = 0;
        guess2 = 0;
        resetbtn.setEnabled(true);
    }//GEN-LAST:event_resetbtnActionPerformed

    private void FinishbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishbtnActionPerformed
        // TODO add your handling code here:
        //used to compare the user entre to the secret numbers

        // Input one
        for (int r = 0; r < rand.length; r++) {
            input1 = Integer.parseInt(numtf.getText());
            if (input1 == rand[r]) {
                guess++;
            }
        }

        //Input two
        for (int r = 0; r < rand.length; r++) {
            input2 = Integer.parseInt(numtf1.getText());
            if (input2 == rand[r]) {
                guess++;
            }
        }

        //Input three
        for (int r = 0; r < rand.length; r++) {
            input3 = Integer.parseInt(numtf2.getText());
            if (input3 == rand[r]) {
                guess++;
            }
        }

        //Input four
        for (int r = 0; r < rand.length; r++) {
            input4 = Integer.parseInt(numtf3.getText());
            if (input4 == rand[r]) {
                guess++;
            }
        }

        //input five
        for (int r = 0; r < rand.length; r++) {
            input5 = Integer.parseInt(numtf4.getText());
            if (input5 == rand[r]) {
                guess++;
            }
        }

        outputar.setText("you guessed " + guess + " right on Lotto");

        Finishbtn.setEnabled(false);
        resetbtn.setEnabled(true);
    }//GEN-LAST:event_FinishbtnActionPerformed

    private void numtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtfActionPerformed

    private void generatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebtnActionPerformed
        // TODO add your handling code here:
        //generates random numnbers
        for (int r = 0; r < rand.length; r++) {
            rand[r] = ThreadLocalRandom.current().nextInt(1, 40 + 1);

        }

        System.out.println("Random numbers");
        System.out.println(Arrays.toString(rand));

        System.out.println(" ");
    }//GEN-LAST:event_generatebtnActionPerformed

    private void numtf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf5ActionPerformed

    private void generatebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebtn1ActionPerformed
        // TODO add your handling code here:
        for (int a = 0; a < randlo.length; a++) {
            randlo[a] = ThreadLocalRandom.current().nextInt(1, 40 + 1);

        }
        System.out.println("Random numbers");
        System.out.println(Arrays.toString(randlo));

        System.out.println(" ");

    }//GEN-LAST:event_generatebtn1ActionPerformed

    private void numtf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf6ActionPerformed

    private void numtf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf7ActionPerformed

    private void numtf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf8ActionPerformed

    private void numtf9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf9ActionPerformed

    private void numtf10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf10ActionPerformed

    private void generatebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebtn2ActionPerformed
        // TODO add your handling code here:
        for (int b = 0; b < rand.length; b++) {
            randlt[b] = ThreadLocalRandom.current().nextInt(1, 40 + 1);

        }
        System.out.println("Random numbers");
        System.out.println(Arrays.toString(randlt));

        System.out.println(" ");

    }//GEN-LAST:event_generatebtn2ActionPerformed

    private void numtf11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf11ActionPerformed

    private void numtf12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf12ActionPerformed

    private void numtf13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf13ActionPerformed

    private void numtf14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf14ActionPerformed

    private void Finishbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finishbtn1ActionPerformed
        // TODO add your handling code here:
        for (int b = 0; b < randlt.length; b++) {
            inputlt1 = Integer.parseInt(numtf10.getText());
            if (inputlt1 == randlo[b]) {
                guess2++;
            }
        }

        //Input two
        for (int b = 0; b < randlt.length; b++) {
            inputlt2 = Integer.parseInt(numtf11.getText());
            if (inputlt2 == randlo[b]) {
                guess2++;
            }
        }

        //Input three
        for (int b = 0; b < randlt.length; b++) {
            inputlt3 = Integer.parseInt(numtf12.getText());
            if (inputlt3 == randlo[b]) {
                guess2++;
            }
        }

        //Input four
        for (int b = 0; b < randlt.length; b++) {
            inputlt4 = Integer.parseInt(numtf13.getText());
            if (inputlt4 == randlo[b]) {
                guess2++;
            }
        }

        //input five
        for (int b = 0; b < randlt.length; b++) {
            inputlt5 = Integer.parseInt(numtf14.getText());
            if (inputlt5 == randlo[b]) {
                guess2++;
            }
        }

        outputar.setText("you guessed " + guess2 + " right on Lotto Plus Two");

        Finishbtn2.setEnabled(false);
        resetbtn.setEnabled(true);
    }//GEN-LAST:event_Finishbtn1ActionPerformed

    private void Finishbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finishbtn2ActionPerformed
        // TODO add your handling code here:
        for (int a = 0; a < randlo.length; a++) {
            inputl1 = Integer.parseInt(numtf5.getText());
            if (inputl1 == randlo[a]) {
                guessl++;
            }
        }

        //Input two
        for (int a = 0; a < randlo.length; a++) {
            inputl2 = Integer.parseInt(numtf6.getText());
            if (inputl2 == randlo[a]) {
                guessl++;
            }
        }

        //Input three
        for (int a = 0; a < randlo.length; a++) {
            inputl3 = Integer.parseInt(numtf7.getText());
            if (inputl3 == randlo[a]) {
                guessl++;
            }
        }

        //Input four
        for (int a = 0; a < randlo.length; a++) {
            inputl4 = Integer.parseInt(numtf8.getText());
            if (inputl4 == randlo[a]) {
                guessl++;
            }
        }

        //input five
        for (int a = 0; a < randlo.length; a++) {
            inputl5 = Integer.parseInt(numtf9.getText());
            if (inputl5 == randlo[a]) {
                guessl++;
            }
        }

        outputar.setText("you guessed " + guessl + " right on lotto Plus One");

        Finishbtn1.setEnabled(false);
        resetbtn.setEnabled(true);

    }//GEN-LAST:event_Finishbtn2ActionPerformed

    private void recordAllbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordAllbtn1ActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String inputl = (numtf5.getText());
        String inputl1 = (numtf6.getText());
        String inputl2 = (numtf7.getText());
        String inputl3 = (numtf8.getText());
        String inputl4 = (numtf9.getText());

        try {

            outFile = new File("SecondPhaseLottoPlusOne.txt");

            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(inputl);
            bw.write(inputl1);
            bw.write(inputl2);
            bw.write(inputl3);
            bw.write(inputl4 + ".....//");
            bw.newLine();

            bw.close();

        } catch (IOException e) {
            errorDisplay.setText("Error writing to Lotto Phase One file" + e);
            System.out.println("Error writing to file" + e);
        }
        status.setText("your Lotto Plus One file was created");

    }//GEN-LAST:event_recordAllbtn1ActionPerformed

    private void recordbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtn1ActionPerformed
        // TODO add your handling code here:
        String inputl;
        String inputl1;
        String inputl2;
        String inputl3;
        String inputl4;

        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("SecondPhaseLottoPlusOne.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            inputl = br.readLine();
            inputl1 = br.readLine();
            inputl2 = br.readLine();
            inputl3 = br.readLine();
            inputl4 = br.readLine();

            recordar.setText(inputl + "...||  " + inputl1 + "...||  " + inputl2 + "...||  " + inputl3 + "...||  " + inputl4);
        } catch (IOException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_recordbtn1ActionPerformed

    private void recordAllbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordAllbtn2ActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String inputlt = (numtf10.getText());
        String inputlt1 = (numtf11.getText());
        String inputlt2 = (numtf12.getText());
        String inputlt3 = (numtf13.getText());
        String inputlt4 = (numtf14.getText());

        try {

            outFile = new File("SecondPhaseLottoPlustwo.txt");

            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(inputlt);
            bw.write(inputlt1);
            bw.write(inputlt2);
            bw.write(inputlt3);
            bw.write(inputlt4 + ".....//");
            bw.newLine();

            bw.close();

        } catch (IOException e) {
            errorDisplay.setText("Error writing to Lotto Plus Two file" + e);
            System.out.println("Error writing to file" + e);
        }
        status.setText("your Lotto Plus Two file was created");

    }//GEN-LAST:event_recordAllbtn2ActionPerformed

    private void recordbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtn2ActionPerformed
        // TODO add your handling code here:
        String inputlt;
        String inputlt1;
        String inputlt2;
        String inputlt3;
        String inputlt4;

        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("SecondPhaseLottoPlusTwo.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            inputlt = br.readLine();
            inputlt1 = br.readLine();
            inputlt2 = br.readLine();
            inputlt3 = br.readLine();
            inputlt4 = br.readLine();

            recordar.setText(inputlt + "...||  " + inputlt1 + "...||  " + inputlt2 + "...||  " + inputlt3 + "...||  " + inputlt4+"...||");
        } catch (IOException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_recordbtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhaseTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhaseTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhaseTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhaseTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhaseTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Finishbtn;
    private javax.swing.JButton Finishbtn1;
    private javax.swing.JButton Finishbtn2;
    private javax.swing.JButton backToHomebtn;
    private javax.swing.JPanel error;
    private javax.swing.JLabel errorDisplay;
    private javax.swing.JLabel filestatus;
    private javax.swing.JButton generatebtn;
    private javax.swing.JButton generatebtn1;
    private javax.swing.JButton generatebtn2;
    private javax.swing.JLabel insertNumberBelowlbl;
    private javax.swing.JLabel insertNumberBelowlbl1;
    private javax.swing.JLabel insertNumberBelowlbl2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lottoGamelbl;
    private javax.swing.JTextField numtf;
    private javax.swing.JTextField numtf1;
    private javax.swing.JTextField numtf10;
    private javax.swing.JTextField numtf11;
    private javax.swing.JTextField numtf12;
    private javax.swing.JTextField numtf13;
    private javax.swing.JTextField numtf14;
    private javax.swing.JTextField numtf2;
    private javax.swing.JTextField numtf3;
    private javax.swing.JTextField numtf4;
    private javax.swing.JTextField numtf5;
    private javax.swing.JTextField numtf6;
    private javax.swing.JTextField numtf7;
    private javax.swing.JTextField numtf8;
    private javax.swing.JTextField numtf9;
    private javax.swing.JTextArea outputar;
    private javax.swing.JButton recordAllbtn;
    private javax.swing.JButton recordAllbtn1;
    private javax.swing.JButton recordAllbtn2;
    private javax.swing.JTextArea recordar;
    private javax.swing.JButton recordbtn;
    private javax.swing.JButton recordbtn1;
    private javax.swing.JButton recordbtn2;
    private javax.swing.JButton resetbtn;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
