/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lottoappphase2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import java.io.*;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author Francis
 */
public class PhaseOne extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form PhaseOne
     */
    public PhaseOne() {
        initComponents();
    }
    //declaring my variables 
    private int secretNum[] = new int[5];
    private int userInterface[][] = new int[3][5];
    ArrayList<Integer> userInNumber = new ArrayList<Integer>();
    ArrayList<ArrayList<Integer>> userNum = new ArrayList<>();//used to gather the numbers the user enters
    private int line1;
    private int line2;
    private int line3;
    Set<Integer> generated = new LinkedHashSet<>();// Note: use LinkedHashSet to maintain insertion order
    ArrayList<Integer> picked = new ArrayList<>();
    int rows, cols;
    String output;
    String userNumberOut = "";
    int input;
    int input1;
    int input2;
    int input3;
    int input4;
    int input5;
    int guess;
    int rand[] = new int[5];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LottoGamelbl = new javax.swing.JLabel();
        numtf = new javax.swing.JTextField();
        insertNumberBelowlbl = new javax.swing.JLabel();
        generatebtn = new javax.swing.JButton();
        error = new javax.swing.JPanel();
        errorDisplay = new javax.swing.JLabel();
        filestatus = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        recordar = new javax.swing.JTextField();
        numtf1 = new javax.swing.JTextField();
        numtf2 = new javax.swing.JTextField();
        numtf3 = new javax.swing.JTextField();
        numtf4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputar = new javax.swing.JTextArea();
        Finishbtn = new javax.swing.JButton();
        recordAllbtn = new javax.swing.JButton();
        recordbtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        backToHomebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(204, 0, 0));

        LottoGamelbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LottoGamelbl.setText("Lotto Game");

        numtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtfActionPerformed(evt);
            }
        });

        insertNumberBelowlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        insertNumberBelowlbl.setForeground(new java.awt.Color(0, 102, 51));
        insertNumberBelowlbl.setText("Insert Number Bellow");

        generatebtn.setBackground(new java.awt.Color(255, 102, 0));
        generatebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generatebtn.setText("Click and Start");
        generatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebtnActionPerformed(evt);
            }
        });

        error.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 7, true));

        errorDisplay.setBackground(new java.awt.Color(102, 102, 0));
        errorDisplay.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        errorDisplay.setForeground(new java.awt.Color(153, 153, 0));
        errorDisplay.setText("All errors will be displayed here");

        status.setBackground(new java.awt.Color(0, 255, 102));
        status.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        status.setForeground(new java.awt.Color(255, 51, 0));
        status.setText("This is the File Status");

        javax.swing.GroupLayout errorLayout = new javax.swing.GroupLayout(error);
        error.setLayout(errorLayout);
        errorLayout.setHorizontalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorLayout.createSequentialGroup()
                .addGroup(errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(457, 457, 457)
                .addComponent(filestatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        errorLayout.setVerticalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filestatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(errorLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(errorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 102, 0), null, null));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Your Record");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(recordar, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        numtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf1ActionPerformed(evt);
            }
        });

        numtf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf2ActionPerformed(evt);
            }
        });

        numtf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf3ActionPerformed(evt);
            }
        });

        numtf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtf4ActionPerformed(evt);
            }
        });

        outputar.setColumns(20);
        outputar.setRows(5);
        jScrollPane2.setViewportView(outputar);

        Finishbtn.setBackground(new java.awt.Color(0, 204, 204));
        Finishbtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Finishbtn.setForeground(new java.awt.Color(204, 0, 0));
        Finishbtn.setText("Finish");
        Finishbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishbtnActionPerformed(evt);
            }
        });

        recordAllbtn.setBackground(new java.awt.Color(153, 0, 0));
        recordAllbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recordAllbtn.setText("save");
        recordAllbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordAllbtnActionPerformed(evt);
            }
        });

        recordbtn.setBackground(new java.awt.Color(255, 255, 0));
        recordbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recordbtn.setText("Display File");
        recordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordbtnActionPerformed(evt);
            }
        });

        resetbtn.setBackground(new java.awt.Color(0, 204, 0));
        resetbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetbtn.setText("reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        backToHomebtn.setBackground(new java.awt.Color(0, 204, 204));
        backToHomebtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        backToHomebtn.setForeground(new java.awt.Color(153, 0, 153));
        backToHomebtn.setText("Home");
        backToHomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LottoGamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Finishbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(numtf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(numtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(numtf2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(numtf3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(numtf4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(recordAllbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(recordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(generatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertNumberBelowlbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backToHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LottoGamelbl)
                        .addGap(1, 1, 1)
                        .addComponent(generatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(insertNumberBelowlbl)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numtf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numtf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numtf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Finishbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recordAllbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backToHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtfActionPerformed

    private void generatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebtnActionPerformed
        // TODO add your handling code here:
        //generates random numnbers
        for (int i = 0; i < secretNum.length; i++) {
            secretNum[i] = (int) Math.floor(1 + Math.random() * 40);
        }
        System.out.println(Arrays.toString(secretNum));
        for (int r = 0; r < rand.length; r++) {
            rand[r] = ThreadLocalRandom.current().nextInt(1, 40 + 1);

        }
        System.out.println("Random numbers");
        System.out.println(Arrays.toString(rand));

        System.out.println(" ");

    }//GEN-LAST:event_generatebtnActionPerformed

    private void backToHomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomebtnActionPerformed
        // TODO add your handling code here:
        //this will send you back to the home
        GameGUI myGUI = new GameGUI();
        myGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backToHomebtnActionPerformed

    private void FinishbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishbtnActionPerformed
         // Input one
        for (int r = 0; r < rand.length; r++) {
            input1 = Integer.parseInt(numtf.getText());
            if (input1 == rand[r]) {
                guess++;
            }
        }

        //Input two
        for (int r = 0; r < rand.length; r++) {
            input2 = Integer.parseInt(numtf1.getText());
            if (input2 == rand[r]) {
                guess++;
            }
        }

        //Input three
        for (int r = 0; r < rand.length; r++) {
            input3 = Integer.parseInt(numtf2.getText());
            if (input3 == rand[r]) {
                guess++;
            }
        }

        //Input four
        for (int r = 0; r < rand.length; r++) {
            input4 = Integer.parseInt(numtf3.getText());
            if (input4 == rand[r]) {
                guess++;
            }
        }

        //input five
        for (int r = 0; r < rand.length; r++) {
            input5 = Integer.parseInt(numtf4.getText());
            if (input5 == rand[r]) {
                guess++;
            }
        }

        outputar.setText("you guessed " + guess + " right");

        Finishbtn.setEnabled(false);
        resetbtn.setEnabled(true);

    }//GEN-LAST:event_FinishbtnActionPerformed

    private void recordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordbtnActionPerformed
        // TODO add your handling code here:
        String input;
        String input1;
        String input2;
        String input3;
        String input4;

        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("FirstPhase.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            input = br.readLine();
            input1 = br.readLine();
            input2 = br.readLine();
            input3 = br.readLine();
            input4 = br.readLine();
            
               
               
            

            recordar.setText(input + "  " + input1 + "  " + input2 + "  " + input3 + "  " + input4);
        } catch (IOException e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_recordbtnActionPerformed

    private void recordAllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordAllbtnActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String input = (numtf.getText());
        String input1 = (numtf1.getText());
        String input2 = (numtf2.getText());
        String input3 = (numtf3.getText());
        String input4 = (numtf4.getText());

        try {

            outFile = new File("FirstPhase.txt");

            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(input);
            bw.write(input1);
            bw.write(input2);
            bw.write(input3);
            bw.write(input4 + ".....//");
            bw.newLine();

            bw.close();

        } catch (IOException e) {
            errorDisplay.setText("Error writing to file" + e);
            System.out.println("Error writing to file" + e);
        }
        status.setText("you file was created");

    }//GEN-LAST:event_recordAllbtnActionPerformed

    private void numtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf1ActionPerformed

    private void numtf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf2ActionPerformed

    private void numtf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf3ActionPerformed

    private void numtf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtf4ActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        Finishbtn.setEnabled(true);
        numtf.setText("");
        numtf1.setText("");
        numtf2.setText("");
        numtf3.setText("");
        numtf4.setText("");
        outputar.setText("");
        guess = 0;
        resetbtn.setEnabled(true);
        recordar.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhaseOne.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhaseOne.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhaseOne.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhaseOne.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhaseOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Finishbtn;
    private javax.swing.JLabel LottoGamelbl;
    private javax.swing.JButton backToHomebtn;
    private javax.swing.JPanel error;
    private javax.swing.JLabel errorDisplay;
    private javax.swing.JLabel filestatus;
    private javax.swing.JButton generatebtn;
    private javax.swing.JLabel insertNumberBelowlbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numtf;
    private javax.swing.JTextField numtf1;
    private javax.swing.JTextField numtf2;
    private javax.swing.JTextField numtf3;
    private javax.swing.JTextField numtf4;
    private javax.swing.JTextArea outputar;
    private javax.swing.JButton recordAllbtn;
    private javax.swing.JTextField recordar;
    private javax.swing.JButton recordbtn;
    private javax.swing.JButton resetbtn;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
